[server]
    port = 9001
    receiveSocketChanLen = 100
    receiveServiceConnChanLen = 120

[redis]
    host = "localhost:6379"
    pwd = ""
    index = 0

[timeWheel]
    cap = 20
    timeout = 5
    noticeChanLen = 200